export const colorMap = {
  indigo: {
    bg: "bg-indigo-50",
    hoverBg: "hover:bg-indigo-100",
    border: "border-indigo-200",
    hoverBorder: "hover:border-indigo-400",
    text: "text-indigo-700",
    accent: "bg-indigo-600",
  },
  sky: {
    bg: "bg-sky-50",
    hoverBg: "hover:bg-sky-100",
    border: "border-sky-200",
    hoverBorder: "hover:border-sky-400",
    text: "text-sky-700",
    accent: "bg-sky-600",
  },
  blue: {
    bg: "bg-sky-50",
    hoverBg: "hover:bg-sky-100",
    border: "border-sky-200",
    hoverBorder: "hover:border-sky-400",
    text: "text-sky-700",
    accent: "bg-sky-600",
  },
  emerald: {
    bg: "bg-emerald-50",
    hoverBg: "hover:bg-emerald-100",
    border: "border-emerald-300",
    hoverBorder: "hover:border-emerald-500",
    text: "text-emerald-700",
    accent: "bg-emerald-600",
  },
  green: {
    bg: "bg-emerald-50",
    hoverBg: "hover:bg-emerald-100",
    border: "border-emerald-300",
    hoverBorder: "hover:border-emerald-500",
    text: "text-emerald-700",
    accent: "bg-emerald-600",
  },
  amber: {
    bg: "bg-amber-50",
    hoverBg: "hover:bg-amber-100",
    border: "border-amber-300",
    hoverBorder: "hover:border-amber-400",
    text: "text-amber-700",
    accent: "bg-amber-600",
  },
  yellow: {
    bg: "bg-amber-50",
    hoverBg: "hover:bg-amber-100",
    border: "border-amber-300",
    hoverBorder: "hover:border-amber-400",
    text: "text-amber-700",
    accent: "bg-amber-600",
  },
  fuchsia: {
    bg: "bg-fuchsia-50",
    hoverBg: "hover:bg-fuchsia-100",
    border: "border-fuchsia-200",
    hoverBorder: "hover:border-fuchsia-400",
    text: "text-fuchsia-700",
    accent: "bg-fuchsia-600",
  },
  cyan: {
    bg: "bg-cyan-50",
    hoverBg: "hover:bg-cyan-100",
    border: "border-cyan-200",
    hoverBorder: "hover:border-cyan-400",
    text: "text-cyan-700",
    accent: "bg-cyan-600",
  },
  orange: {
    bg: "bg-orange-50",
    hoverBg: "hover:bg-orange-100",
    border: "border-orange-200",
    hoverBorder: "hover:border-orange-400",
    text: "text-orange-700",
    accent: "bg-orange-600",
  },
  teal: {
    bg: "bg-orange-50",
    hoverBg: "hover:bg-orange-100",
    border: "border-orange-200",
    hoverBorder: "hover:border-orange-400",
    text: "text-orange-700",
    accent: "bg-orange-600",
  },
  rose: {
    bg: "bg-rose-50",
    hoverBg: "hover:bg-rose-100",
    border: "border-rose-200",
    hoverBorder: "hover:border-rose-400",
    text: "text-rose-700",
    accent: "bg-rose-600",
  },
  purple: {
    bg: "bg-purple-100/70",
    hoverBg: "hover:bg-purple-100",
    border: "border-purple-300",
    hoverBorder: "hover:border-purple-500",
    text: "text-purple-800",
    accent: "bg-purple-700",
  },
  violet: {
    bg: "bg-purple-100/70",
    hoverBg: "hover:bg-purple-100",
    border: "border-purple-300",
    hoverBorder: "hover:border-purple-500",
    text: "text-purple-800",
    accent: "bg-purple-700",
  },
};